name: flutter_package_template
version: 1.0.0
homepage: https://github.com/marchdev-tk/flutter_package_template
repository: https://github.com/marchdev-tk/flutter_package_template
issue_tracker: https://github.com/marchdev-tk/flutter_package_template/issues
description: flutter_package_template description

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
